/*
  Appointment server actions for Luxe Skin Clinic
  - Uses Supabase for data persistence (no local fallback)
  - Optional Resend integration for email notifications
*/

'use server';

import { supabaseAdmin, isSupabaseConfigured } from '@/lib/supabase';
import { resend, isResendConfigured } from '@/lib/resend';

// Appointment data model
export interface Appointment {
  id: string;
  full_name: string;
  email: string;
  phone: string;
  gender: string;
  age: number;
  service: string;
  appointment_date: string; // YYYY-MM-DD
  appointment_time: string; // e.g., "10:00 AM"
  message?: string;
  status: 'pending' | 'confirmed' | 'cancelled';
  created_at: string; // ISO timestamp
}

/**
 * Create a new appointment and store it in Supabase.
 * Returns success flag, the created appointment, optional email status, and a message.
 */
export async function createAppointment(
  formData: Omit<Appointment, 'id' | 'status' | 'created_at'>
) {
  // ---------- Validation ---------------------------------------------------
  if (!formData.full_name?.trim() || formData.full_name.trim().length < 2) {
    return { success: false, error: 'Full name is required (minimum 2 characters).' };
  }
  if (!formData.email || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(formData.email)) {
    return { success: false, error: 'A valid email address is required.' };
  }
  if (!formData.phone?.trim() || formData.phone.trim().length < 8) {
    return { success: false, error: 'A valid phone number is required.' };
  }
  if (!formData.gender) {
    return { success: false, error: 'Please select a gender.' };
  }
  if (formData.age == null || formData.age < 1 || formData.age > 120) {
    return { success: false, error: 'Please enter a valid age.' };
  }
  if (!formData.service) {
    return { success: false, error: 'Please select a service.' };
  }
  if (!formData.appointment_date) {
    return { success: false, error: 'Please pick an appointment date.' };
  }
  if (!formData.appointment_time) {
    return { success: false, error: 'Please select an appointment time.' };
  }

  // ---------- Supabase configuration check ---------------------------------
  if (!isSupabaseConfigured || !supabaseAdmin) {
    console.error('Supabase configuration missing.');
    return { success: false, error: 'Supabase is not configured. Please set environment variables.' };
  }

  // ---------- Build appointment object --------------------------------------
  const newAppointment: Appointment = {
    id: crypto.randomUUID(), // temporary, will be overwritten by Supabase ID
    ...formData,
    status: 'pending',
    created_at: new Date().toISOString(),
  };

  // ---------- Insert into Supabase ------------------------------------------
  const { data, error } = await supabaseAdmin
    .from('appointments')
    .insert([
      {
        full_name: formData.full_name,
        email: formData.email,
        phone: formData.phone,
        gender: formData.gender,
        age: formData.age,
        service: formData.service,
        appointment_date: formData.appointment_date,
        appointment_time: formData.appointment_time,
        message: formData.message || '',
        status: 'pending',
      },
    ])
    .select()
    .single();

  if (error) {
    console.error('Supabase insert error details:', error);
    return { success: false, error: `Failed to save appointment: ${error.message || 'unknown error'}` };
  }

  // Use the ID generated by Supabase if present
  if (data && data.id) {
    newAppointment.id = data.id;
  }

  // ---------- Optional Resend email integration -----------------------------
  let emailsSent = false;
  if (isResendConfigured && resend) {
    try {
      const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';
      const doctorEmail = process.env.DOCTOR_NOTIFICATION_EMAIL || 'doctor@example.com';
      // Notify clinic staff
      await resend.emails.send({
        from: `Luxe Skin Clinic <${fromEmail}>`,
        to: doctorEmail,
        subject: 'New Appointment Booking Request',
        html: `<p>New booking from ${formData.full_name} for ${formData.service} on ${formData.appointment_date} at ${formData.appointment_time}.</p>`,
      });
      // Confirmation email to patient
      await resend.emails.send({
        from: `Luxe Skin Clinic <${fromEmail}>`,
        to: formData.email,
        subject: 'Appointment Confirmation',
        html: `<p>Dear ${formData.full_name}, your appointment for ${formData.service} has been received and is pending confirmation.</p>`,
      });
      emailsSent = true;
    } catch (e) {
      console.error('Resend email failed:', e);
    }
  }

  return {
    success: true,
    appointment: newAppointment,
    emailsSent,
    message: 'Appointment booked successfully! Confirmation emails have been sent.',
  };
}

/** Retrieve all appointments for the admin dashboard. */
export async function getAppointments() {
  if (!isSupabaseConfigured || !supabaseAdmin) {
    console.error('Supabase not configured while fetching appointments.');
    return [] as Appointment[];
  }
  const { data, error } = await supabaseAdmin
    .from('appointments')
    .select('*')
    .order('appointment_date', { ascending: true });
  if (error) {
    console.error('Supabase fetch error:', error);
    return [] as Appointment[];
  }
  return data as Appointment[];
}

/** Update the status of an appointment. */
export async function updateAppointmentStatus(
  id: string,
  status: 'pending' | 'confirmed' | 'cancelled'
) {
  if (!isSupabaseConfigured || !supabaseAdmin) {
    console.error('Supabase not configured while updating status.');
    return { success: false, error: 'Supabase not configured.' };
  }
  const { error } = await supabaseAdmin
    .from('appointments')
    .update({ status })
    .eq('id', id);
  if (error) {
    console.error('Supabase update error:', error);
    return { success: false, error: error.message };
  }
  return { success: true };
}

/** Delete an appointment. */
export async function deleteAppointment(id: string) {
  if (!isSupabaseConfigured || !supabaseAdmin) {
    console.error('Supabase not configured while deleting appointment.');
    return { success: false, error: 'Supabase not configured.' };
  }
  const { error } = await supabaseAdmin
    .from('appointments')
    .delete()
    .eq('id', id);
  if (error) {
    console.error('Supabase delete error:', error);
    return { success: false, error: error.message };
  }
  return { success: true };
}
